# Cross-platform testing for md2html-action
# Tests the action on multiple operating systems to ensure compatibility

name: Cross-Platform Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cross-platform-tests:
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Action on ${{ matrix.os }}
        id: test
        uses: ./
        with:
          source-dir: "test-docs"
          output-dir: "outputs-cross-platform-test"
          site-title: "Cross-Platform Test Site"

      - name: Verify Output on ${{ matrix.os }}
        shell: bash
        run: |
          echo "Files converted: ${{ steps.test.outputs.files-converted }}"
          echo "Output path: ${{ steps.test.outputs.output-path }}"

          # Check that HTML files were created
          if [ ! -f "outputs-cross-platform-test/index.html" ]; then
            echo "ERROR: index.html not created on ${{ matrix.os }}"
            exit 1
          fi

          if [ ! -f "outputs-cross-platform-test/getting-started.html" ]; then
            echo "ERROR: getting-started.html not created on ${{ matrix.os }}"
            exit 1
          fi

          if [ ! -f "outputs-cross-platform-test/advanced/configuration.html" ]; then
            echo "ERROR: advanced/configuration.html not created on ${{ matrix.os }}"
            exit 1
          fi

          # Check that CSS file exists
          if [ ! -f "outputs-cross-platform-test/style.css" ]; then
            echo "ERROR: style.css not created on ${{ matrix.os }}"
            exit 1
          fi

          # Check that media files were copied
          if [ ! -f "outputs-cross-platform-test/media/favicon.ico" ]; then
            echo "ERROR: media files not copied on ${{ matrix.os }}"
            exit 1
          fi

          echo "✅ All tests passed on ${{ matrix.os }}!"

      - name: Upload Cross-Platform Test Results
        uses: actions/upload-artifact@v4
        with:
          name: outputs-cross-platform-test-${{ matrix.os }}
          path: outputs-cross-platform-test/
          retention-days: 5
