# Integration tests for the md2html-action
# Tests different configuration scenarios to ensure the action works correctly

name: Integration Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test-default-configuration:
    runs-on: ubuntu-latest
    name: Test default configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert Markdown to HTML (default settings)
        id: convert
        uses: ./ # Use local action for testing
        with:
          source-dir: "test-docs"
          output-dir: "outputs-default-configuration"

      - name: Verify output
        run: |
          echo "Files converted: ${{ steps.convert.outputs.files-converted }}"
          echo "Output path: ${{ steps.convert.outputs.output-path }}"
          ls -la outputs-default-configuration/

          # Verify key files exist
          test -f outputs-default-configuration/index.html || (echo "ERROR: index.html missing" && exit 1)
          test -f outputs-default-configuration/getting-started.html || (echo "ERROR: getting-started.html missing" && exit 1)
          test -f outputs-default-configuration/advanced/configuration.html || (echo "ERROR: configuration.html missing" && exit 1)

          echo "✅ Default configuration test passed!"

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs-default-configuration
          path: outputs-default-configuration/
          retention-days: 7

  test-custom-configuration:
    runs-on: ubuntu-latest
    name: Test custom configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert with custom settings
        id: convert
        uses: ./
        with:
          source-dir: "test-docs"
          output-dir: "outputs-custom-configuration"
          template: "minimal"
          stylesheet: "minimal"
          site-title: "Custom Test Documentation"
          include-toc: "true"
          pandoc-options: "--highlight-style=tango"

      - name: Verify custom output
        run: |
          echo "Files converted: ${{ steps.convert.outputs.files-converted }}"
          ls -la outputs-custom-configuration/

          # Verify files exist with custom settings
          test -f outputs-custom-configuration/index.html || (echo "ERROR: custom index.html missing" && exit 1)

          echo "✅ Custom configuration test passed!"

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs-custom-configuration
          path: outputs-custom-configuration/
          retention-days: 7

  test-remote-css:
    runs-on: ubuntu-latest
    name: Test remote CSS integration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert with remote stylesheet
        id: convert
        uses: ./
        with:
          source-dir: "test-docs"
          output-dir: "outputs-remote-css"
          template: "github"
          stylesheet: "https://cdn.jsdelivr.net/npm/github-markdown-css@5.1.0/github-markdown.min.css"
          site-title: "Remote GitHub CSS Demo"

      - name: Verify remote CSS integration
        run: |
          echo "Files converted: ${{ steps.convert.outputs.files-converted }}"
          ls -la outputs-remote-css/

          # Verify files exist
          test -f outputs-remote-css/index.html || (echo "ERROR: remote CSS index.html missing" && exit 1)

          echo "✅ Remote CSS integration test passed!"

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs-remote-css
          path: outputs-remote-css/
          retention-days: 7

  test-academic-style:
    runs-on: ubuntu-latest
    name: Test academic stylesheet
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert with academic stylesheet
        id: convert
        uses: ./
        with:
          source-dir: "test-docs"
          output-dir: "outputs-academic-style"
          stylesheet: "academic"
          site-title: "Academic Documentation"
          include-toc: "true"

      - name: Verify academic output
        run: |
          echo "Files converted: ${{ steps.convert.outputs.files-converted }}"
          ls -la outputs-academic-style/

          # Verify files exist
          test -f outputs-academic-style/index.html || (echo "ERROR: academic index.html missing" && exit 1)
          test -f outputs-academic-style/style.css || (echo "ERROR: academic style.css missing" && exit 1)

          echo "✅ Academic stylesheet test passed!"

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs-academic-style
          path: outputs-academic-style/
          retention-days: 7

  test-technical-style:
    runs-on: ubuntu-latest
    name: Test technical stylesheet
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert with technical stylesheet
        id: convert
        uses: ./
        with:
          source-dir: "test-docs"
          output-dir: "outputs-technical-style"
          stylesheet: "technical"
          site-title: "Technical Documentation"
          include-toc: "true"

      - name: Verify technical output
        run: |
          echo "Files converted: ${{ steps.convert.outputs.files-converted }}"
          ls -la outputs-technical-style/

          # Verify files exist
          test -f outputs-technical-style/index.html || (echo "ERROR: technical index.html missing" && exit 1)
          test -f outputs-technical-style/style.css || (echo "ERROR: technical style.css missing" && exit 1)

          echo "✅ Technical stylesheet test passed!"

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs-technical-style
          path: outputs-technical-style/
          retention-days: 7

  test-blog-style:
    runs-on: ubuntu-latest
    name: Test blog stylesheet
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert with blog stylesheet
        id: convert
        uses: ./
        with:
          source-dir: "test-docs"
          output-dir: "outputs-blog-style"
          stylesheet: "blog"
          site-title: "Blog Documentation"
          include-toc: "true"

      - name: Verify blog output
        run: |
          echo "Files converted: ${{ steps.convert.outputs.files-converted }}"
          ls -la outputs-blog-style/

          # Verify files exist
          test -f outputs-blog-style/index.html || (echo "ERROR: blog index.html missing" && exit 1)
          test -f outputs-blog-style/style.css || (echo "ERROR: blog style.css missing" && exit 1)

          echo "✅ Blog stylesheet test passed!"

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs-blog-style
          path: outputs-blog-style/
          retention-days: 7

  test-corporate-style:
    runs-on: ubuntu-latest
    name: Test corporate stylesheet
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert with corporate stylesheet
        id: convert
        uses: ./
        with:
          source-dir: "test-docs"
          output-dir: "outputs-corporate-style"
          stylesheet: "corporate"
          site-title: "Corporate Documentation"
          include-toc: "true"

      - name: Verify corporate output
        run: |
          echo "Files converted: ${{ steps.convert.outputs.files-converted }}"
          ls -la outputs-corporate-style/

          # Verify files exist
          test -f outputs-corporate-style/index.html || (echo "ERROR: corporate index.html missing" && exit 1)
          test -f outputs-corporate-style/style.css || (echo "ERROR: corporate style.css missing" && exit 1)

          echo "✅ Corporate stylesheet test passed!"

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs-corporate-style
          path: outputs-corporate-style/
          retention-days: 7
